---
# file: roles/hubot/tasks/main.yml

- name: Install CoffeeScript
  sudo: yes
  npm: name=coffee-script global=yes

- name: Install hubot
  sudo: yes
  npm: name=hubot global=yes

- name: Install redis
  sudo: yes
  yum: name=redis state=present

- name: Start redis
  sudo: yes
  service: name=redis state=started enabled=yes

